services:
  # Next.js Application
  app:
    image: 762907076445.dkr.ecr.ap-southeast-2.amazonaws.com/art-store:1.0.0
    container_name: art-store-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://namratha:Kartha%401128@cluster2.azyzvwp.mongodb.net/?retryWrites=true&w=majority
      - TOKEN_SECRET=your-super-secret-jwt-token-key-change-this-in-production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - art-store-network
    volumes:
      - ./public:/app/public:ro

networks:
  art-store-network:
    driver: bridge
